# Instalando bibliotecas necessárias

O ! indica que você está executando um comando de terminal (shell) dentro do notebook.

Ou seja, em vez de rodar código Python, você está rodando algo equivalente a isso no terminal:

In [2]:
!pip install fsspec polars paramiko

Requirement already satisfied: fsspec in ./venv/lib/python3.12/site-packages (2026.2.0)
Requirement already satisfied: polars in ./venv/lib/python3.12/site-packages (1.39.3)
Requirement already satisfied: paramiko in ./venv/lib/python3.12/site-packages (4.0.0)
Requirement already satisfied: polars-runtime-32==1.39.3 in ./venv/lib/python3.12/site-packages (from polars) (1.39.3)
Requirement already satisfied: bcrypt>=3.2 in ./venv/lib/python3.12/site-packages (from paramiko) (5.0.0)
Requirement already satisfied: cryptography>=3.3 in ./venv/lib/python3.12/site-packages (from paramiko) (46.0.5)
Requirement already satisfied: invoke>=2.0 in ./venv/lib/python3.12/site-packages (from paramiko) (2.2.1)
Requirement already satisfied: pynacl>=1.5 in ./venv/lib/python3.12/site-packages (from paramiko) (1.6.2)
Requirement already satisfied: cffi>=2.0.0 in ./venv/lib/python3.12/site-packages (from cryptography>=3.3->paramiko) (2.0.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=3.3->paramiko) (3.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

# Imports

Aqui importamos as bibliotecas que instalamos para usar no código

In [4]:
import polars as pl
import fsspec
import io

Esse trecho está criando uma conexão com um sistema de arquivos remoto via SFTP, usando o fsspec como camada de abstração.

“Me dê um objeto que saiba acessar arquivos via SFTP nesse servidor.”

In [5]:
fs = fsspec.filesystem("sftp", 
                       host="localhost", 
                       port=2222, 
                       username="teste", 
                       password="123456")

Esse trecho faz a leitura de um arquivo remoto (via SFTP) e converte os bytes em texto legível.

In [6]:
with fs.open("/upload/microdados_enem_2024/DADOS/RESULTADOS_2024.csv", "rb") as f:
    content = f.read()

text = content.decode("latin-1")

Lê o conteúdo de texto do CSV (já decodificado) a partir de um buffer em memória (`StringIO`) e o transforma em um DataFrame do Polars usando `;` como separador.

In [7]:
df_resultado = pl.read_csv(io.StringIO(text), separator=";")

executando a variavel que contém o dataframe o jupyter print uma pequena parte da tabela, notem que no canto superior esquerdo temos o shape (quantidade de linhas e colunas) da tabela

In [11]:
df_resultado

shape: (4_332_944, 42)
┌────────────┬────────┬───────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ NU_SEQUENC ┆ NU_ANO ┆ CO_ESCOLA ┆ CO_MUNICIP ┆ … ┆ NU_NOTA_C ┆ NU_NOTA_C ┆ NU_NOTA_C ┆ NU_NOTA_R │
│ IAL        ┆ ---    ┆ ---       ┆ IO_ESC     ┆   ┆ OMP3      ┆ OMP4      ┆ OMP5      ┆ EDACAO    │
│ ---        ┆ i64    ┆ i64       ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64        ┆        ┆           ┆ i64        ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
╞════════════╪════════╪═══════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 206403     ┆ 2024   ┆ 23052929  ┆ 2301406    ┆ … ┆ 60        ┆ 80        ┆ 20        ┆ 300       │
│ 3604651    ┆ 2024   ┆ 42103770  ┆ 4218004    ┆ … ┆ 200       ┆ 180       ┆ 180       ┆ 920       │
│ 1461268    ┆ 2024   ┆ null      ┆ null       ┆ … ┆ 40        ┆ 120       ┆ 80        ┆ 480       │
│ 4301058    ┆ 2024   ┆ null      ┆ null       ┆ … ┆ 160       ┆ 160       ┆ 80        ┆ 740       │
│ 3148322    ┆ 2024   ┆ 21150354  ┆ 2100436    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ …          ┆ …      ┆ …         ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1966623    ┆ 2024   ┆ null      ┆ null       ┆ … ┆ 120       ┆ 140       ┆ 140       ┆ 640       │
│ 1661560    ┆ 2024   ┆ null      ┆ null       ┆ … ┆ 80        ┆ 80        ┆ 20        ┆ 420       │
│ 2464303    ┆ 2024   ┆ 35923874  ┆ 3522505    ┆ … ┆ 120       ┆ 100       ┆ 120       ┆ 580       │
│ 3164695    ┆ 2024   ┆ 33025150  ┆ 3301306    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 3131550    ┆ 2024   ┆ null      ┆ null       ┆ … ┆ 140       ┆ 160       ┆ 180       ┆ 780       │
└────────────┴────────┴───────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Como fazer Filtros e Selecionar colunas em um daframe polars

Para selecionar colunas usamos o metodo .select() e passamos no parametro o nome das colunas conforme o exemplo

In [12]:
df_resultado.select(
    'NU_SEQUENCIAL',
    'NU_ANO',
    'CO_ESCOLA',
    'CO_MUNICIPIO_ESC',
    'NO_MUNICIPIO_ESC',
    'CO_UF_ESC'
)

shape: (4_332_944, 6)
┌───────────────┬────────┬───────────┬──────────────────┬─────────────────────────┬───────────┐
│ NU_SEQUENCIAL ┆ NU_ANO ┆ CO_ESCOLA ┆ CO_MUNICIPIO_ESC ┆ NO_MUNICIPIO_ESC        ┆ CO_UF_ESC │
│ ---           ┆ ---    ┆ ---       ┆ ---              ┆ ---                     ┆ ---       │
│ i64           ┆ i64    ┆ i64       ┆ i64              ┆ str                     ┆ i64       │
╞═══════════════╪════════╪═══════════╪══════════════════╪═════════════════════════╪═══════════╡
│ 206403        ┆ 2024   ┆ 23052929  ┆ 2301406          ┆ Aratuba                 ┆ 23        │
│ 3604651       ┆ 2024   ┆ 42103770  ┆ 4218004          ┆ Tijucas                 ┆ 42        │
│ 1461268       ┆ 2024   ┆ null      ┆ null             ┆ null                    ┆ null      │
│ 4301058       ┆ 2024   ┆ null      ┆ null             ┆ null                    ┆ null      │
│ 3148322       ┆ 2024   ┆ 21150354  ┆ 2100436          ┆ Alto Alegre do Maranhão ┆ 21        │
│ …             ┆ …      ┆ …         ┆ …                ┆ …                       ┆ …         │
│ 1966623       ┆ 2024   ┆ null      ┆ null             ┆ null                    ┆ null      │
│ 1661560       ┆ 2024   ┆ null      ┆ null             ┆ null                    ┆ null      │
│ 2464303       ┆ 2024   ┆ 35923874  ┆ 3522505          ┆ Itapevi                 ┆ 35        │
│ 3164695       ┆ 2024   ┆ 33025150  ┆ 3301306          ┆ Casimiro de Abreu       ┆ 33        │
│ 3131550       ┆ 2024   ┆ null      ┆ null             ┆ null                    ┆ null      │
└───────────────┴────────┴───────────┴──────────────────┴─────────────────────────┴───────────┘

também temos como selecionar usando o método .col() do polars, a diferença pro anterior é que usando o método .col() podemos usar uma serie de outros métodos, ou seja temos mais opções de manipulação

In [15]:
df_resultado.select(
    pl.col("NU_SEQUENCIAL").alias("chave primária"),
    pl.col("NU_ANO").alias("Ano"),
    pl.col("CO_ESCOLA").alias("codigo da escola"),
    pl.col("CO_MUNICIPIO_ESC"),
    pl.col("NO_MUNICIPIO_ESC"),
    pl.col("CO_UF_ESC"),
)

shape: (4_332_944, 6)
┌────────────────┬──────┬──────────────────┬──────────────────┬───────────────────┬───────────┐
│ chave primária ┆ Ano  ┆ codigo da escola ┆ CO_MUNICIPIO_ESC ┆ NO_MUNICIPIO_ESC  ┆ CO_UF_ESC │
│ ---            ┆ ---  ┆ ---              ┆ ---              ┆ ---               ┆ ---       │
│ i64            ┆ i64  ┆ i64              ┆ i64              ┆ str               ┆ i64       │
╞════════════════╪══════╪══════════════════╪══════════════════╪═══════════════════╪═══════════╡
│ 206403         ┆ 2024 ┆ 23052929         ┆ 2301406          ┆ Aratuba           ┆ 23        │
│ 3604651        ┆ 2024 ┆ 42103770         ┆ 4218004          ┆ Tijucas           ┆ 42        │
│ 1461268        ┆ 2024 ┆ null             ┆ null             ┆ null              ┆ null      │
│ 4301058        ┆ 2024 ┆ null             ┆ null             ┆ null              ┆ null      │
│ 3148322        ┆ 2024 ┆ 21150354         ┆ 2100436          ┆ Alto Alegre do    ┆ 21        │
│                ┆      ┆                  ┆                  ┆ Maranhão          ┆           │
│ …              ┆ …    ┆ …                ┆ …                ┆ …                 ┆ …         │
│ 1966623        ┆ 2024 ┆ null             ┆ null             ┆ null              ┆ null      │
│ 1661560        ┆ 2024 ┆ null             ┆ null             ┆ null              ┆ null      │
│ 2464303        ┆ 2024 ┆ 35923874         ┆ 3522505          ┆ Itapevi           ┆ 35        │
│ 3164695        ┆ 2024 ┆ 33025150         ┆ 3301306          ┆ Casimiro de Abreu ┆ 33        │
│ 3131550        ┆ 2024 ┆ null             ┆ null             ┆ null              ┆ null      │
└────────────────┴──────┴──────────────────┴──────────────────┴───────────────────┴───────────┘

In [ ]:
with fs.open("/upload/microdados_enem_2024/DADOS/ITENS_PROVA_2024.csv", "rb") as f:
    content = f.read()

text = content.decode("latin-1")

df_itens_prova = pl.read_csv(io.StringIO(text), separator=";")

In [ ]:
df_itens_prova

shape: (5_550, 14)
┌────────────┬─────────┬─────────┬─────────────┬───┬─────────┬──────────┬───────────┬──────────────┐
│ CO_POSICAO ┆ SG_AREA ┆ CO_ITEM ┆ TX_GABARITO ┆ … ┆ TX_COR  ┆ CO_PROVA ┆ TP_LINGUA ┆ IN_ITEM_ADAP │
│ ---        ┆ ---     ┆ ---     ┆ ---         ┆   ┆ ---     ┆ ---      ┆ ---       ┆ TADO         │
│ i64        ┆ str     ┆ i64     ┆ str         ┆   ┆ str     ┆ i64      ┆ str       ┆ ---          │
│            ┆         ┆         ┆             ┆   ┆         ┆          ┆           ┆ i64          │
╞════════════╪═════════╪═════════╪═════════════╪═══╪═════════╪══════════╪═══════════╪══════════════╡
│ 6          ┆ LC      ┆ 150678  ┆ E           ┆ … ┆ AZUL    ┆ 1395     ┆ null      ┆ 0            │
│ 7          ┆ LC      ┆ 14475   ┆ D           ┆ … ┆ AZUL    ┆ 1353     ┆ null      ┆ 0            │
│ 7          ┆ LC      ┆ 14475   ┆ D           ┆ … ┆ AZUL    ┆ 1441     ┆ null      ┆ 0            │
│ 7          ┆ LC      ┆ 16575   ┆ A           ┆ … ┆ AMARELA ┆ 1354     ┆ null      ┆ 0            │
│ 7          ┆ LC      ┆ 16575   ┆ A           ┆ … ┆ AMARELA ┆ 1442     ┆ null      ┆ 0            │
│ …          ┆ …       ┆ …       ┆ …           ┆ … ┆ …       ┆ …        ┆ …         ┆ …            │
│ 176        ┆ MT      ┆ 17549   ┆ E           ┆ … ┆ CINZA   ┆ 1326     ┆ null      ┆ 0            │
│ 176        ┆ MT      ┆ 17549   ┆ E           ┆ … ┆ CINZA   ┆ 1366     ┆ null      ┆ 0            │
│ 176        ┆ MT      ┆ 27923   ┆ A           ┆ … ┆ AMARELA ┆ 1324     ┆ null      ┆ 0            │
│ 176        ┆ MT      ┆ 27923   ┆ A           ┆ … ┆ AMARELA ┆ 1364     ┆ null      ┆ 0            │
│ 176        ┆ MT      ┆ 76177   ┆ D           ┆ … ┆ AMARELA ┆ 1408     ┆ null      ┆ 0            │
└────────────┴─────────┴─────────┴─────────────┴───┴─────────┴──────────┴───────────┴──────────────┘

shape: (0, 6)
┌───────────────┬───────────┬────────────────────┬─────────────────┬────────────┬─────────┐
│ NU_SEQUENCIAL ┆ SG_UF_ESC ┆ NO_MUNICIPIO_PROVA ┆ TX_RESPOSTAS_CN ┆ NU_NOTA_CN ┆ TP_SEXO │
│ ---           ┆ ---       ┆ ---                ┆ ---             ┆ ---        ┆ ---     │
│ i64           ┆ str       ┆ str                ┆ str             ┆ f64        ┆ str     │
╞═══════════════╪═══════════╪════════════════════╪═════════════════╪════════════╪═════════╡
└───────────────┴───────────┴────────────────────┴─────────────────┴────────────┴─────────┘

In [ ]:
df_resultado.columns

['NU_SEQUENCIAL',
 'SG_UF_ESC',
 'NO_MUNICIPIO_PROVA',
 'TX_RESPOSTAS_CN',
 'NU_NOTA_CN']

In [ ]:
df_participantes

shape: (4_332_944, 38)
┌──────────────┬────────┬─────────────────┬─────────┬───┬──────┬──────┬──────┬──────┐
│ NU_INSCRICAO ┆ NU_ANO ┆ TP_FAIXA_ETARIA ┆ TP_SEXO ┆ … ┆ Q020 ┆ Q021 ┆ Q022 ┆ Q023 │
│ ---          ┆ ---    ┆ ---             ┆ ---     ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ i64          ┆ i64    ┆ i64             ┆ str     ┆   ┆ str  ┆ str  ┆ str  ┆ str  │
╞══════════════╪════════╪═════════════════╪═════════╪═══╪══════╪══════╪══════╪══════╡
│ 210062064233 ┆ 2024   ┆ 5               ┆ F       ┆ … ┆ B    ┆ B    ┆ E    ┆ A    │
│ 210062064234 ┆ 2024   ┆ 11              ┆ F       ┆ … ┆ B    ┆ A    ┆ C    ┆ A    │
│ 210062064235 ┆ 2024   ┆ 11              ┆ F       ┆ … ┆ B    ┆ A    ┆ D    ┆ A    │
│ 210062064236 ┆ 2024   ┆ 3               ┆ F       ┆ … ┆ B    ┆ A    ┆ D    ┆ A    │
│ 210062064237 ┆ 2024   ┆ 16              ┆ M       ┆ … ┆ B    ┆ A    ┆ B    ┆ A    │
│ …            ┆ …      ┆ …               ┆ …       ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
│ 210066495575 ┆ 2024   ┆ 7               ┆ M       ┆ … ┆ B    ┆ A    ┆ C    ┆ A    │
│ 210066495576 ┆ 2024   ┆ 6               ┆ M       ┆ … ┆ B    ┆ A    ┆ C    ┆ A    │
│ 210066495577 ┆ 2024   ┆ 4               ┆ F       ┆ … ┆ B    ┆ B    ┆ B    ┆ A    │
│ 210066495578 ┆ 2024   ┆ 2               ┆ F       ┆ … ┆ A    ┆ A    ┆ B    ┆ A    │
│ 210066495579 ┆ 2024   ┆ 1               ┆ F       ┆ … ┆ B    ┆ A    ┆ D    ┆ D    │
└──────────────┴────────┴─────────────────┴─────────┴───┴──────┴──────┴──────┴──────┘